del "temporary data.json"
del "temporary data.pkl"
del "temporary data.bin"
del "Summoner Traversal on *.xlsx"
del "Interactions.json"
del "Recently Played Summoners in Lobby *.xlsx"
del "Recently Played Summoners in Match *.xlsx"
del "Recent ChampSelect Summoners in Match *.xlsx"
del "Recently Played Summoners in Friend List of *.xlsx"
del "Recently Played Summoners in Friend Requests of *.xlsx"
del "Recently Played Summoners in Invitations to and from *.xlsx"
del "Recently Played Summoners in Block List of *.xlsx"
del "Recently Played Summoners in Specified Player List - *.xlsx"
del "GameTypeConfig.json"
del "Perks.xlsx"
del "Recommended Page.json"
del "MyPage.json"
del "Player Stats in Match *.xlsx"
del "lobby-information.json"
del "matchmaking-search.json"
del "readyCheck.json"
del "champ-select-session.json"
del "gameflow-session.json"
del "inGame_data.xlsx"
del "allgamedata.json"
del "honor-ballot.json"
del "currentSequenceEvent.json"
del "EndOfGame Stats of *.xlsx"
del "ItemSet.txt"
del "ItemSet.json"
del "ItemPage - *.txt"
del "ItemPage - *.json"
