del "temporary data.json"
del "temporary data.pkl"
del "Recently Played Summoners in Friend List.xlsx"
del "Recently Played Summoners in Friend Requests.xlsx"
del "Recently Played Summoners in Specified Player List.xlsx"
del /s "Recently Played Summoners *.xlsx"
del "GameTypeConfig.json"
del "Perks.xlsx"
del "Recommended Page.json"
del "MyPage.json"
del "Player Stats in Match *.xlsx"
del "lobby-information.json"
del "matchmaking-search.json"
del "readyCheck.json"
del "champ-select-session.json"
del "honor-ballot.json"
del "currentSequenceEvent.json"
del "EndOfGame Stats of *.xlsx"
