from lcu_driver import Connector
from lcu_driver.connection import Connection
from lcu_driver.exceptions import NoLeagueClientDetected
import asyncio
from asyncio import AbstractEventLoop
from typing import Any, Callable, Awaitable, Optional

ConnectionCallBack = Callable[[Connection], Awaitable[None]]

def LCUConnect(on_ready: ConnectionCallBack, on_close: Optional[ConnectionCallBack] = None, loop: Optional[AbstractEventLoop] = None) -> None: #DeepSeek生成后调整（Modified after being generated by DeepSeek）
    '''
    通过新建事件循环允许在程序的同一个生命周期内反复连接至联盟客户端。<br>By creating new event loops, this function allows the program to connect to League Client repetitively with the same lifecycle.
    
    :param on_ready: 准备就绪时要调用的连接函数。<br>A connect function to call on ready.
    
        该函数应当只接受一个连接对象，并不返回任何值。<br>This function should only accept a Connection object and shouldn't return any value.
    :type on_ready: Callable[[Connection], Awaitable[None]]
    :param on_close: 关闭连接时要调用的断开连接函数。<br>A disconnect function to call on close.
    
        该函数应当只接受一个连接对象，并不返回任何值。<br>This function should only accept a Connection object and shouldn't return any value.
    :type on_close: Callable[[Connection], Awaitable[None]]
    :param loop: 手动指定事件循环。目前尚未启用。<br>Manually specify an event loop. Not enabled for now.
    :type loop: AbstractEventLoop
    '''
    connector: Connector = Connector()
    
    #-----------------------------------------------------------------------------
    # websocket
    #-----------------------------------------------------------------------------
    @connector.ready
    async def connect(connection: Connection) -> None:
        await on_ready(connection)
    
    if on_close:
        @connector.close
        async def disconnect(connection: Connection) -> None:
            await on_close(connection)
    else:
        @connector.close
        async def disconnect(connection: Connection) -> None:
            print("已从英雄联盟客户端断开连接。\nDisconnected from the League Client.")
    
    #-----------------------------------------------------------------------------
    # Main
    #-----------------------------------------------------------------------------
    try:
        connector.start()
    except NoLeagueClientDetected:
        print("未检测到运行中的英雄联盟客户端。\nNo League Client is found running.")
    else:
        new_loop: AbstractEventLoop = asyncio.new_event_loop()
        asyncio.set_event_loop(new_loop)

if __name__ == "__main__": #调试（Debug）
    async def my_custom_connect(connection: Connection) -> None: #用户自定义的连接回调（User-defined connection callback）
        print("连接已就绪。执行自定义任务……\nConnection is ready. Perform a custom task ...")
        current_summoner: dict[str, Any] = await (await connection.request("GET", "/lol-summoner/v1/current-summoner")).json()
        print("您好，召唤师：", end = "")
        print(current_summoner["gameName"] + "#" + current_summoner["tagLine"])
        print("Hello, summoner: ", end = "")
        print(current_summoner["gameName"] + "#" + current_summoner["tagLine"])

    async def my_custom_disconnect(_: Connection) -> None: #用户自定义的断开连接回调（User-defined disconnection callback）
        print("执行自定义清理工作……\nPerform custom clearing task ...")

    LCUConnect(on_ready = my_custom_connect, on_close = my_custom_disconnect)
